const form = document.querySelector('.hero form')
const input = document.querySelector('#dog-name')
const headerText = document.querySelector('.hero h1 strong')
console.log('form: ', form)
console.log('input: ', input)
console.log('headerText: ', headerText)
